services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-erp-php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mini-erp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp
      MYSQL_USER: erpuser
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  adminer:
    image: adminer
    container_name: mini-erp-adminer
    restart: always
    ports:
      - "8081:8080"
